# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/jandel/Documents/Linux_Unreal_Engine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	CITA_417_FPS_Lab-Android-DebugGame  \
	CITA_417_FPS_Lab-Android-Development  \
	CITA_417_FPS_Lab-Android-Shipping  \
	CITA_417_FPS_Lab-Linux-DebugGame  \
	CITA_417_FPS_Lab-Linux-Development  \
	CITA_417_FPS_Lab-Linux-Shipping  \
	CITA_417_FPS_Lab-LinuxArm64-DebugGame  \
	CITA_417_FPS_Lab-LinuxArm64-Development  \
	CITA_417_FPS_Lab-LinuxArm64-Shipping  \
	CITA_417_FPS_Lab \
	CITA_417_FPS_LabEditor-Linux-DebugGame  \
	CITA_417_FPS_LabEditor-Linux-Development  \
	CITA_417_FPS_LabEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CITA_417_FPS_LabEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CITA_417_FPS_LabEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

CITA_417_FPS_Lab-Android-DebugGame:
	 $(BUILD) CITA_417_FPS_Lab Android DebugGame  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-Android-Development:
	 $(BUILD) CITA_417_FPS_Lab Android Development  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-Android-Shipping:
	 $(BUILD) CITA_417_FPS_Lab Android Shipping  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-Linux-DebugGame:
	 $(BUILD) CITA_417_FPS_Lab Linux DebugGame  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-Linux-Development:
	 $(BUILD) CITA_417_FPS_Lab Linux Development  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-Linux-Shipping:
	 $(BUILD) CITA_417_FPS_Lab Linux Shipping  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-LinuxArm64-DebugGame:
	 $(BUILD) CITA_417_FPS_Lab LinuxArm64 DebugGame  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-LinuxArm64-Development:
	 $(BUILD) CITA_417_FPS_Lab LinuxArm64 Development  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab-LinuxArm64-Shipping:
	 $(BUILD) CITA_417_FPS_Lab LinuxArm64 Shipping  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_Lab: CITA_417_FPS_Lab-Linux-Development

CITA_417_FPS_LabEditor-Linux-DebugGame:
	 $(BUILD) CITA_417_FPS_LabEditor Linux DebugGame  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_LabEditor-Linux-Development:
	 $(BUILD) CITA_417_FPS_LabEditor Linux Development  -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" $(ARGS)

CITA_417_FPS_LabEditor: CITA_417_FPS_LabEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/jandel/Documents/Unreal Projects/CITA_417_FPS_Lab/CITA_417_FPS_Lab.uproject" -Game 

.PHONY: $(TARGETS)
